apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-service-account
  namespace: devops-tools
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: jenkins-role
#   namespace: devops-tools
#   labels:
#     "app.kubernetes.io/name": 'jenkins'
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/exec"]
#   verbs: ["create","delete","get","list","patch","update","watch"]
# - apiGroups: [""]
#   resources: ["pods/log"]
#   verbs: ["get","list","watch"]
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["get"]
# - apiGroups: [""]
#   resources: ["serviceaccounts"]
#   verbs: ["get", "create"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: jenkins-role-binding
#   namespace: devops-tools
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: jenkins-role
# subjects:
# - kind: ServiceAccount
#   name: jenkins-service-account
#   namespace: devops-tools
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: jenkins-admin-secret
#   namespace: devops-tools
#   annotations:
#     kubernetes.io/service-account.name: "jenkins-service-account"   
# type: kubernetes.io/service-account-token  